### PR TITLE
Clean up the encyclopedia pages

### PR DESCRIPTION
**Pull request by PoPoWanObi**
Relocated the buttons to the right side of the encyclopedia to make them feel more uniform.

Also added in mod configuration setting to enable or disable the label for "DCC Options" on the encyclopedia. It's enabled by default, but can be disabled for experienced users who are aware of which buttons DCC adds, to keep the page looking clean.

image
image
image
image

### CODE REVIEW

**Comment by PoPoWanObi** [comment]
This should finish this PR. I'm sure other improvements could be made, but this appears to be working as intended. Just a little aesthetic improvements. I'm looking into the official developer tools to see what can/cannot be done with those.


Off topic::
It does not appear that the eng_module_strings.xml is being used; however I could be mistaken?

Is the translations feature currently working? @Designer225

**Comment by Designer225** [comment]
@PoPoWanObi I don't know if the English language files ever worked, but I do know there are several translations that takes advantage of the game's built-in localization feature ever since localization support was added (beforehand translations would have to modify the mod's source code instead), so it's probably working.

As for the feature, it's nice, although depending on the resolution some breakage may appear 😝
image

I don't think it's a big deal, but we should probably use a scaling number on it.

**Comment by PoPoWanObi** [comment]
Yeah, I tried it on a 4:3 resolution and 16:9. The breakage was acceptable on 4:3, as it just floated it above the Encyclopedia. I wasn't too concerned for non-standard resolutions; but yes, ideally getting it into a fixed placement that respects all aspect ratios would be preferred.

**Comment by Designer225** [comment]
Okay, whenever it's ready, let me know and I'll test it and then push it out. DCC is currently on Steam Workshop, so if you have a Steam account, I can add you as a contributor.

It is not known if Bannerlord's Steam Workshop program allows updating the mod as a contributor. You can give it a try.

**Comment by PoPoWanObi** [comment]
No worries about adding as a collaborator, the workshop only allows the creator to publish changes. Not too worried about it, since we can both access the Git. I'll play around with the sizing and see what I can do.

**Comment by PoPoWanObi** [comment]
Please give this a test and let me know. I tried all of the resolutions my game client had available and it worked fine for me.

**Comment by PoPoWanObi** [comment]
I've gone ahead and updated the FOMOD to support both Vortex and MO2. No need to play around with multiple releases on the mod page :)

**Comment by Designer225** [comment]
Finalized patch note. Merging.

**Pull request merged**
