### PR TITLE
Much needed code update for e1.3 and later (but mostly e1.4)

### PR DESCRIPTION
**Pull request by Designer225**
* The code had to be fixed for e1.3 and later because it was broken by the former update.
* Some refactoring was done in the process.
* A questionable use of C# reflection in `Patches/DynamicBodyPatch.cs` was modified.

The code should work for e1.4 and later.

Please update DCC, @PoPoWanObi. I had to create a hotfix for the mod users, but I can't keep hold down the fort without edit permission...

### CODE REVIEW

**Comment by PoPoWanObi** [comment]
Thanks for stepping up. Unfortunately I've been waiting a month for my PSU to arrive, so I haven't had the chance to update this. My computer I've been using is too old to run M&B.

I'll push the update in a bit here, if you give me your Nexus name I'll give you edit permissions (if you want).

I won't be able to verify if everything is working or not until PSU for my newer hardware however.

Screenshot at 06-27-02

**Comment by Designer225** [comment]
Huh, so you've been waiting for the PSU to arrive. That explains long period of no updates, although it would be great to notify the users that you have been having hardware problems instead of radio silence...

I forgot to mention that skins.xml has been updated for e1.3. I have crudely updated both the [version without the new sliders](https://pastebin.com/pArjjVvh) and the [one with them added](https://pastebin.com/qRewNfZj).

I'm thinking of integrating some of my patches from [my two](https://www.nexusmods.com/mountandblade2bannerlord/mods/595) [other mods](https://www.nexusmods.com/mountandblade2bannerlord/mods/1068). One of the patches works around the problem of children being (almost) untouchable in "missions" (e.g. battles), and another tries to fix spawned child agents looking like adults. (Yeah, TaleWorlds changed the game.) As long as you are active, I don't think edit permission is necessary, but if you may, I use the same Nexus name as on GitHub (Designer225).

**Comment by PoPoWanObi** [comment]
You're right very unprofessional.

I just got burnt out then PC issues. Been just relaxing waiting for parts to arrive amid covid.

DCC never had the intention of permitting players to play as children, only customizing them if players wanted. There's a lot of issues with playing as children, and the devs clearly don't want people to either, hence the no damage bug.

I'd restrict DCC to Character Customization settings and properties, and leave everything else as external, but we can update the information/guides with those addons for those who "do" wish to play as children.

**Comment by PoPoWanObi** [comment]
On another note; if you design them to be modular (configurable --> default off) we can discuss it further and whether or not they fit into DCC or not.

**Comment by PoPoWanObi** [comment]
For the skins.xml I'll be working on those as soon as I am able.

Unfortunately all this delay has interrupted my work on a new FaceGen window, but eventually the skins.xml won't be required anymore.

**Comment by Designer225** [comment]
Well, it's good to hear all of this. I'll keep my patches on separate mods for now. Most of them are in [this mod](https://www.nexusmods.com/mountandblade2bannerlord/mods/1068), and patches in those can be switched off. But you already know about [this one](https://www.nexusmods.com/mountandblade2bannerlord/mods/595).

I'll instead work on localization for your mod and do some more code refactoring.

**Pull request merged**
