### PR TITLE
Fix Mod Options Screen

### PR DESCRIPTION
**Pull request by Aragas**
Added Harmony as a NuGet package
Replaced ``ModLib`` with ``Bannerlord.MBOptionScreen``, fixes the loading issue.

You'll need to add to [SubModule.xml](https://github.com/Aragas/Bannerlord.MBOptionScreen/wiki/Editing-SubModule.xml) the mod. The reason for it is to avoid dependencies. ``Bannerlord.MBOptionScreen`` can work as a standalone mod and as an inclided submodule!

So it will work if your mod is the ony mod installed, if ``Bannerlord.MBOptionScreen`` is installed as a standalone module together with you mod and if several mods integrate ``Bannerlord.MBOptionScreen``

Works.

### CODE REVIEW

**Comment by Aragas** [comment]
Feel free to ask any questions! I will provide you any support that you'll need with the module.
You can check [this](https://github.com/Aragas/Bannerlord.MBOptionScreen/wiki/Comparing-to-ModLib) to see the differences between both modules!

**Comment by PoPoWanObi** [comment]
Thanks for doing this! It's much cleaner as well!

I'm not sure what you mean with the XML however, unless you mean it should require this:
<. SubModuleClassType value="MBOptionScreen.MBOptionScreenSubModule" />

**Comment by Aragas** [comment]
You're welcome!
I meant that the actual settings are saved in the game's default config folder as JSON files

**Comment by PoPoWanObi** [comment]
Not sure if it's something I did, but the mod doesn't appear in mod options anymore.

**Comment by Aragas** [comment]
The line you mentioned is optional. Either you include ``Bannerlord.MBOptionScreen`` in your mod to remove any external dependencies or rely on the user to have it installed as a standalone mod. Still need to create the standalone mod tho.

**Comment by Aragas** [comment]
It might be SubModule.xml. I didn't found it in your repos, so I have used a local one.

Does your SubModule.xml look like this?
<details>
  <summary>SubModule.xml</summary>
  
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Module>
   <Name value="Detailed Character Creation" />
   <Id value="zzCharacterCreation" />
   <Version value="v1.0.9" />
   <SingleplayerModule value="true" />
   <MultiplayerModule value="false" />
   <DependedModules>
      <DependedModule Id="Native" />
      <DependedModule Id="SandBoxCore" />
      <DependedModule Id="Sandbox" />
      <DependedModule Id="CustomBattle" />
      <DependedModule Id="StoryMode" />
   </DependedModules>
   <SubModules>
      <SubModule>
         <Name value="CharacterCreation" />
         <DLLName value="CharacterCreation.dll" />
         <SubModuleClassType value="CharacterCreation.SubModule" />
         <Tags>
            <Tag key="DedicatedServerType" value="none" />
            <Tag key="IsNoRenderModeElement" value="false" />
         </Tags>
      </SubModule>
      <SubModule>
         <Name value="MBOptionScreen" />
         <DLLName value="MBOptionScreen.dll" />
         <SubModuleClassType value="MBOptionScreen.MBOptionScreenSubModule" />
         <Tags>
            <Tag key="DedicatedServerType" value="none" />
            <Tag key="IsNoRenderModeElement" value="false" />
         </Tags>
      </SubModule>
   </SubModules>
   <Xmls>
      <XmlNode>
         <XmlName id="strings" path="strings" />
         <IncludedGameTypes>
            <GameType value="Campaign" />
            <GameType value="CampaignStoryMode" />
         </IncludedGameTypes>
      </XmlNode>
   </Xmls>
</Module>
```
  
</details>

**Comment by PoPoWanObi** [comment]
Hmm. That just causes ctd.

**Comment by Aragas** [comment]
The issue might be that ``0Harmony.dll`` and ``MBOptionScreen.dll`` are not copied yo the output folder. You must inlude them in /bin/Win64_Shipping_Client!
Check #2

**Comment by PoPoWanObi** [comment]
They are there!

**Comment by PoPoWanObi** [comment]
Screenshot at 13-37-40

**Comment by Aragas** [comment]
That's weird! Can you try my working one just to confirm that it work in your environment?

[zzCharacterCreation.zip](https://github.com/PoPoWanObi/CharacterCreation/files/4488863/zzCharacterCreation.zip)

**Comment by PoPoWanObi** [comment]
Crashes as well.

**Comment by Aragas** [comment]
Are any other mods enabled? Seems to be an interesting issue.
If you do, could you zip all of them and send them so I could try to replicate the issue?

**Comment by PoPoWanObi** [comment]
I've only got ModLib, Bannerlord Tweaks and this activated.
[Modules.zip](https://github.com/PoPoWanObi/CharacterCreation/files/4488908/Modules.zip)

**Comment by Aragas** [comment]
Just started up!
Could you try to remove ModLib? Maybe it couldn't load the config files or something?
<details>
  <summary>Image</summary>



</details>

**Comment by PoPoWanObi** [comment]
Alas, even with just DCC enabled it ctds.

Everything else runs without issue. Hmm.

**Comment by Aragas** [comment]
Can you send me the crash dump file then? It does contain some info about your machine, so could you send me it via [Nexus?](https://www.nexusmods.com/users/2355906)

**Comment by PoPoWanObi** [comment]
Sent it, didn't find anything useful myself.

**Comment by Aragas** [comment]
Found something interesting! Are you using the latest stable release?

**Comment by PoPoWanObi** [comment]
of which? Visual Studio?

**Comment by Aragas** [comment]
The game!

**Comment by PoPoWanObi** [comment]
Oh. I am not. I'll give that a try. I turned off automatic updates via steam, and didn't see if there was a new update.

**Comment by Aragas** [comment]
Please do tell what version it was, it seem to have missing some API and I'm curious which version caused that

**Comment by PoPoWanObi** [comment]
1.0.10 or 1.0.11, unsure actually
But one of those two.

**Comment by Aragas** [comment]
I'll create a workaround for this anyway, gimme a sec

**Comment by PoPoWanObi** [comment]
Alright after update working fine. 👍

**Comment by Aragas** [comment]
That's great!

**Pull request merged**
